[package]
name = "rust-criu-protobuf"
version = "0.1.0"
edition = "2021"

[dependencies]
protobuf = "3.2.0"

[build-dependencies]
protobuf-codegen = "3.2.0"

[lib]
name = "rust_criu_protobuf"
path = "src/mod.rs"
